// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgK1n_V4jjMJj2KTMFqd3LiV8b71i-ayE',
    appId: '1:355712914316:web:ac1c94345e295dc6487ca9',
    messagingSenderId: '355712914316',
    projectId: 'emailpasswordauth-ac363',
    authDomain: 'emailpasswordauth-ac363.firebaseapp.com',
    storageBucket: 'emailpasswordauth-ac363.appspot.com',
    measurementId: 'G-QV5PY98L31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMOGAkIGiItK8U9sGzWzNhan15q12bhI',
    appId: '1:355712914316:android:3fae124f3dd34c4e487ca9',
    messagingSenderId: '355712914316',
    projectId: 'emailpasswordauth-ac363',
    storageBucket: 'emailpasswordauth-ac363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByd2H4uh9AHGqPWC5sCHcaisdHpGvYGIM',
    appId: '1:355712914316:ios:cbfea7775004bad4487ca9',
    messagingSenderId: '355712914316',
    projectId: 'emailpasswordauth-ac363',
    storageBucket: 'emailpasswordauth-ac363.appspot.com',
    iosClientId: '355712914316-8tm1unv59rgps6h5guaj963fsuhdbt5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1New',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByd2H4uh9AHGqPWC5sCHcaisdHpGvYGIM',
    appId: '1:355712914316:ios:cbfea7775004bad4487ca9',
    messagingSenderId: '355712914316',
    projectId: 'emailpasswordauth-ac363',
    storageBucket: 'emailpasswordauth-ac363.appspot.com',
    iosClientId: '355712914316-8tm1unv59rgps6h5guaj963fsuhdbt5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1New',
  );
}
